### PR TITLE
Added colon separated time support

### PR DESCRIPTION
**Pull request by barinali**
This branch covers #24.

I don't know why @stuartpb closed his pull request, but I wanted to mention him anyway. Because I just refactored his code block a little bit and added some tests to cover the feature.

### CODE REVIEW

**Comment by stuartpb** [comment]
I closed #24? Still looks open to me.

**Comment by stuartpb** [comment]
Worth noting that the closed pull request in question was #25, which was written to close #24

**Comment by stuartpb** [comment]
Okay, this was *four years ago*, so it's a bit of a challenge for me to remember back to when I wrote the PR, but if I remember correctly, the reason I closed it was because, on testing, the parsing failed because ms.js didn't actually handle mixed times (ie. it could handle `3h` or `4m` but not `3h4m`). It's possible that's changed since the original PR, but from what I remember, that was the failure I experienced with the code submitted in #25.

**Comment by stuartpb** [comment]
Yeah, I'm pretty sure that's what it was - and, for that reason, *this* PR is busted, too: you're *returning a rewritten string* when given the parse input (a rewritten string that, from what I can tell, *would not parse to the correct time* if you passed it back in to `ms()`).

**Comment by stuartpb** [comment]
The issue in question was raised in #54

**Comment by rauchg** [comment]
Not a fan of this. Seems out of scope for `ms`

**Comment by rauchg** [comment]
Thank for the proposal!

**Pull request closed without merging**
